FROM public.ecr.aws/lambda/python:3.9

# Copy function code
COPY app/models.py ${LAMBDA_TASK_ROOT}/app/
COPY app/utils/response_utils.py ${LAMBDA_TASK_ROOT}/app/utils/
COPY migrations/ ${LAMBDA_TASK_ROOT}/migrations/
COPY alembic.ini ${LAMBDA_TASK_ROOT}

# Clean up the Python compilation cache
RUN find ${LAMBDA_TASK_ROOT} -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete

# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY requirements_migrations.txt  .
RUN  pip3 install --upgrade pip
RUN  pip3 install -r requirements_migrations.txt --target "${LAMBDA_TASK_ROOT}"

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "migrations.migrations.handler" ]
