version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - 9000:8080
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'app.py'

  dbmigration:
    build:
      context: .
      dockerfile: Dockerfile_migrations
    ports:
      - 9001:8080
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'migrations.py'
    restart: on-failure
    depends_on:
      - db
    links:
      - db

  github_webhook:
    build:
      context: .
      dockerfile: Dockerfile_app_webhook
    ports:
      - 9002:8080
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'app_webhook.py'

  post_confirmation:
    build:
      context: .
      dockerfile: Dockerfile_post_confirmation_hook
    ports:
      - 9003:8080
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'app_post_confirmation.py'
