version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  post_confirmation:
    build:
      context: .
      dockerfile: Dockerfile_post_confirmation_hook
    ports:
      - 9003:8080
    environment:
      DATABASE_URL: 'postgresql://pluto:pluto@db:5432/pluto'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'app_post_confirmation.py'
