FROM public.ecr.aws/lambda/python:3.9

# Install the function's dependencies using file requirements.txt
# from your project folder.
COPY requirements_db_setup.txt  .
RUN  pip3 install --upgrade pip
RUN  pip3 install -r requirements_db_setup.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY migrations/app_db_setup.py ${LAMBDA_TASK_ROOT}/migrations/
COPY app/utils/response_utils.py ${LAMBDA_TASK_ROOT}/app/utils/
COPY app/models.py ${LAMBDA_TASK_ROOT}/app/

# Clean up the Python compilation cache
RUN find ${LAMBDA_TASK_ROOT} -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "migrations.app_db_setup.handler" ]
