version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  github_webhook:
    build:
      context: .
      dockerfile: Dockerfile_app_webhook
    ports:
      - 9002:8080
    environment:
      DATABASE_URL: 'postgresql://pluto:pluto@db:5432/pluto'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'app_webhook.py'
