version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  dbmigration:
    build:
      context: .
      dockerfile: Dockerfile_migrations
    ports:
      - 9001:8080
    environment:
      DATABASE_URL: 'postgresql://pluto:pluto@db:5432/pluto'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'migrations.py'
    restart: on-failure
    depends_on:
      - db
    links:
      - db

  dbsetup:
    build:
      context: .
      dockerfile: Dockerfile_db_setup
    ports:
      - 9004:8080
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'
      PYTHONUNBUFFERED: 'TRUE'
      FLASK_APP: 'migrations.py'
    restart: on-failure
    depends_on:
      - db
    links:
      - db
