"""Add email columns to users

Revision ID: 0d8ba0f58205
Revises: 72130e9ca41c
Create Date: 2021-10-14 14:58:48.493249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8ba0f58205'
down_revision = '72130e9ca41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_account', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_column('user_account', 'email')
    op.drop_column('project_user', 'email')
    # ### end Alembic commands ###
