"""Initial db schema

Revision ID: 42468b51e768
Revises: 
Create Date: 2021-09-30 12:41:43.349996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42468b51e768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
