"""Add installation id for the user and org

Revision ID: 700ff4e6aafb
Revises: 0d8ba0f58205
Create Date: 2021-10-19 09:31:30.445187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700ff4e6aafb'
down_revision = '0d8ba0f58205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('installation_id', sa.String(), nullable=False))
    op.add_column('project_user', sa.Column('installation_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user', 'installation_id')
    op.drop_column('organisation', 'installation_id')
    # ### end Alembic commands ###
