"""Initial db migration

Revision ID: c94f5d2a07da
Revises: 
Create Date: 2021-10-05 10:07:36.910733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c94f5d2a07da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('organisation',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('repository',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user_account',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project_board',
    sa.Column('project_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('board_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['board_uuid'], ['board.uuid'], ),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('project_uuid', 'board_uuid')
    )
    op.create_table('project_owner',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organisation_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('project_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_uuid'], ['organisation.uuid'], ),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user_account.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_uuid', 'organisation_uuid', 'project_uuid')
    )
    op.create_table('project_repository',
    sa.Column('project_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('repository_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ),
    sa.ForeignKeyConstraint(['repository_uuid'], ['repository.uuid'], ),
    sa.PrimaryKeyConstraint('project_uuid', 'repository_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_repository')
    op.drop_table('project_owner')
    op.drop_table('project_board')
    op.drop_table('user_account')
    op.drop_table('repository')
    op.drop_table('project')
    op.drop_table('organisation')
    op.drop_table('board')
    # ### end Alembic commands ###
