"""Move code to the user link

Revision ID: f63653750ae5
Revises: ffce900d2d8a
Create Date: 2021-10-21 13:46:22.914369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63653750ae5'
down_revision = 'ffce900d2d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user', 'code')
    op.add_column('user_link', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_link', 'code')
    op.add_column('project_user', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
