"""Add project user roken columns

Revision ID: ffce900d2d8a
Revises: 700ff4e6aafb
Create Date: 2021-10-20 13:14:40.888106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffce900d2d8a'
down_revision = '700ff4e6aafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user', sa.Column('code', sa.String(), nullable=True))
    op.add_column('project_user', sa.Column('personal_access_token', sa.String(), nullable=True))
    op.add_column('project_user', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user', 'refresh_token')
    op.drop_column('project_user', 'personal_access_token')
    op.drop_column('project_user', 'code')
    # ### end Alembic commands ###
