name: Acceptance tests
on:
  push:
    branches: [main, task/5-run-acceptance-tests]
jobs:
  smoketests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Robot tests
        uses: joonvena/robotframework-docker-action@v1.0
      - name: upload reports
        uses: actions/upload-artifact@v2
          with:
            name: reports
            path: reports