name: Acceptance tests
on:
  workflow_run:
    workflows: ["Development workflow"]
    types: [completed]
  push:

jobs:
  robot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run robot tests
        run: docker-compose --project-directory robot run robot
        env:
          SERVER: https://pluto-dev.rnd.eficode.io
          ROBOT_USERNAME: ${{ secrets.ROBOT_USERNAME }}
          ROBOT_PASSWORD: ${{ secrets.ROBOT_PASSWORD }}
          ROBOT_GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_TOKEN }}
      - name: upload reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: robot/reports

  reports:
    needs: [ robot ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send reports to commit
        uses: joonvena/robotframework-reporter-action@v1.0
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
