name: Acceptance tests
on:
  workflow_run:
    workflows: ["Development workflow"]
    types: [completed]
jobs:

  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Robot tests
        run: |
          bash run_robot_tests.sh
        env:
          TEST_ACCOUNT_USERNAME: pluto.tester@eficode.invalid
          TEST_ACCOUNT_PASSWORD: ${{ secrets.TEST_ACCOUNT_PASSWORD }}
          URL: https://pluto-dev.rnd.eficode.io/
      - name: upload reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: reports

  generate_report:
    if: always()
    needs: [ acceptance_tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v1.0
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
