name: Build and deploy lambdas
on:
  push:
    branches: [main, build_lambdas_zip_files]
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build lambda zip file and update pluto-development-api lambda
        run: |
          bash zip_api_lambda.sh
          bash deploy_lambda_from_zip.sh
        env:
          FUNCTION_NAME: pluto-development-api
          ALIAS: development
          DESCRIPTION: ${{ steps.extract_branch.outputs.branch }}-1.0.${{ github.run_number }}-api
          S3_BUCKET: ${{ secrets.S3_BACKEND_BUCKET_NAME }}
          S3_ZIP_FILE: ${{ steps.extract_branch.outputs.branch }}-1.0.${{ github.run_number }}-api.zip
          S3_PATH: 'api'
  build-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build lambda zip file and update pluto-development-migrations lambda
        run: |
          bash zip_migrations_lambda.sh
          bash deploy_lambda_from_zip.sh
        env:
          FUNCTION_NAME: pluto-development-migrations
          ALIAS: development
          DESCRIPTION: ${{ steps.extract_branch.outputs.branch }}-1.0.${{ github.run_number }}-migrations
          S3_BUCKET: ${{ secrets.S3_BACKEND_BUCKET_NAME }}
          S3_ZIP_FILE: ${{ steps.extract_branch.outputs.branch }}-1.0.${{ github.run_number }}-migrations.zip
          S3_PATH: 'migrations'
      - name: Invoke pluto-development-migrations lambda
        run: |
          bash invoke_migrations_lambda.sh
        env:
          FUNCTION_NAME: pluto-development-migrations
          ALIAS: development
