name: Development workflow
on:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node_version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Configure AWS config file
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "region=$DEV_AWS_REGION" >> ~/.aws/config
        env:
          DEV_AWS_REGION: eu-west-1
      - name: Configure AWS credentials file
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=$DEV_AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key=$DEV_AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_session_token=$DEV_AWS_SESSION_TOKEN" >> ~/.aws/credentials
        env:
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          DEV_AWS_SESSION_TOKEN: ${{ secrets.DEV_AWS_SESSION_TOKEN }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Install Amplify CLI & Deploy Project
        run: |
          npm install -g @aws-amplify/cli --unsafe-perm=true
          bash pull.sh
          bash push.sh
