name: Development workflow
on:
  push:
    branches: [main]
jobs:
  deploy:
    strategy:
      matrix:
        node_version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Configure AWS
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: eu-west-1
          key: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pipenv & Amplify CLI
        run: |
          pip3 install --user pipenv
          npm install -g @aws-amplify/cli --unsafe-perm=true
          npm ci
      - name: Pull Project
        run: |
          bash pull.sh
      - name: Push Project
        run: |
          bash push.sh
        env:
          REACT_APP_USER_POOL_ID: ${{ secrets.DEV_USER_POOL_ID }}
          REACT_APP_USER_POOL_CLIENT_ID: ${{ secrets.DEV_USER_POOL_CLIENT_ID }}
          REACT_APP_REGION: eu-west-1
          REACT_APP_PROJECT_API_URL: https://api.pluto-dev.rnd.eficode.io/development
          REACT_APP_GITHUB_APP_INSTALLATION_URL: https://github.com/apps/pluto-application/installations/new/
