name: Deploy development lambda
on:
  workflow_run:
    workflows: ["Build and deploy to ECR"]
    types: [completed]
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Configure AWS
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: eu-west-1
          key: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Update pluto-development-api lambda
        run: |
          bash deploy_ldambda.sh
        env:
          ECR_URL: ${{ steps.login-ecr.outputs.registry }}
          FUNCTION_NAME: pluto-development-api
          ALIAS: development
          DESCRIPTION: ${{ steps.extract_branch.outputs.branch }}-1.0.${{ github.run_number }}-api
          ECR_REPO: pluto-backend
          ECR_IMAGE: ${{ steps.extract_branch.outputs.branch }}-1.0.${{ github.run_number }}-api
