name: Development workflow
on:
  push:
    branches: [main, fix_pull_and_push]
jobs:
  deploy:
    strategy:
      matrix:
        node_version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Configure AWS
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: eu-west-1
          key: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli --unsafe-perm=true
          npm ci
      - name: Pull Project
        run: |
          bash pull.sh
      - name: Push Project
        run: |
          bash push.sh
