name: 'Run full ZAP scan'
on:
  workflow_dispatch:
  schedule:
    # Runs every Monday 10:30 UTC
    - cron: '30 10 * * 1'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://pluto-dev.rnd.eficode.io/'
